branches:
  except:
  - appveyor
  - actions

language: cpp

addons:
  apt:
    packages:
    - libsdl2-dev

matrix:
  include:
    # Xcode 12.0.1 on macOS 10.15.7
    - os: osx
      osx_image: xcode12

    # Xcode 13.1 on macOS 11.6
    - os: osx
      osx_image: xcode13.1

    # Ubuntu 20.04 LTS, gcc, x64
    - os: linux
      dist: focal
      compiler: gcc

    # Ubuntu 20.04 LTS, Clang, x64
    - os: linux
      dist: focal
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export SDL_VERSION=2.0.20;
      curl -LO https://github.com/libsdl-org/SDL/releases/download/release-${SDL_VERSION}/SDL2-${SDL_VERSION}.dmg;
      hdiutil attach SDL2-${SDL_VERSION}.dmg;
      sudo cp -r /Volumes/SDL2/SDL2.framework /Library/Frameworks;
    fi

before_script:
  - cmake --version

script:
  - mkdir build && cd build
  - cmake ..
  - make
